services:
  # PHP Application Service (Laravel)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    network_mode: host

  # Nginx Web Server Service
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    network_mode: host

  # PostgreSQL Database Service
  db:
    image: postgres:latest
    container_name: laravel_postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT_FORWARD:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
    network_mode: host

# MinIO S3 Compatible Storage Service
  minio:
    image: minio/minio:latest
    container_name: laravel_minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_API_PORT: ${MINIO_API_PORT}
    volumes:
      - minio_data:/data
    command: server /data --address ":${MINIO_API_PORT:-9000}" --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    healthcheck:
      test: ["CMD", "curl", "-f", "${MINIO_ENDPOINT}/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    network_mode: host

  # Service to create a Minio bucket on startup
  create_minio_bucket:
    build:
      context: .
      dockerfile: docker/minio_client/Dockerfile.minio_client
    container_name: minio_bucket_creator
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_API_PORT: ${MINIO_API_PORT}
    command: >
      "while ! mc alias set local ${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} --api S3v4 2>/dev/null; do
      echo 'Aguardando MinIO ficar pronto...';
      sleep 5;
      done;
      mc mb local/${MINIO_BUCKET_NAME};
      mc policy set public local/${MINIO_BUCKET_NAME};
      echo 'Bucket configurado com sucesso';"
    network_mode: host


# Docker Volumes (for data persistence)
volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
