
CREATE TABLE pessoa (
  pes_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pes_nome VARCHAR(200),
  pes_data_nascimento DATE,
  pes_sexo VARCHAR(9),
  pes_mae VARCHAR(200),
  pes_pai VARCHAR(200)
);

CREATE TABLE foto_pessoa (
  fp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pes_id INTEGER NOT NULL UNIQUE REFERENCES pessoa(pes_id),
  fp_data DATE,
  fp_bucket VARCHAR(50),
  fp_hash VARCHAR(50)
);

CREATE TABLE cidade (
  cid_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cid_nome VARCHAR(200),
  cid_uf VARCHAR(2)
);

CREATE TABLE endereco (
  end_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  end_tipo_logradouro VARCHAR(50),
  end_logradouro VARCHAR(200),
  end_numero INTEGER,
  end_bairro VARCHAR(100),
  cid_id INTEGER REFERENCES cidade(cid_id)
);

CREATE TABLE pessoa_endereco (
  pes_id INTEGER REFERENCES pessoa(pes_id),
  end_id INTEGER REFERENCES endereco(end_id),
  PRIMARY KEY (pes_id, end_id)
);

CREATE TABLE servidor_temporario (
  pes_id INTEGER REFERENCES pessoa(pes_id),
  st_data_admissao DATE NOT NULL,
  st_data_demissao DATE
);

CREATE TABLE servidor_efetivo (
  pes_id INTEGER REFERENCES pessoa(pes_id),
  se_matricula VARCHAR(20)
);

CREATE TABLE unidade (
  unid_id INTEGER INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unid_nome VARCHAR(200),
  unid_sigla VARCHAR(20)
);

CREATE TABLE lotacao (
  lot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pes_id INTEGER REFERENCES pessoa(pes_id),
  unid_id INTEGER REFERENCES unidade(unid_id),
  lot_data_lotacao DATE NOT NULL,
  lot_data_remocao DATE,
  lot_portaria VARCHAR(100)
);

CREATE TABLE unidade_endereco (
  unid_id INTEGER REFERENCES unidade(unid_id),
  end_id INTEGER REFERENCES endereco(end_id),
  PRIMARY KEY (unid_id, end_id)
);


