CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE migrations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration VARCHAR(255) NOT NULL,
    batch INT NOT NULL
);

CREATE TABLE sessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

CREATE TABLE cache (
    id SERIAL PRIMARY KEY,
    store VARCHAR(255) NOT NULL,
    key VARCHAR(255) NOT NULL UNIQUE,
    value TEXT NOT NULL,
    expiration TIMESTAMP NOT NULL
);

CREATE TABLE personal_access_tokens (
    id BIGSERIAL PRIMARY KEY,
    tokenable_id BIGINT NOT NULL,
    tokenable_type VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    token VARCHAR(64) NOT NULL,
    abilities TEXT,
    last_used_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT personal_access_tokens_token_unique UNIQUE (token)
);

-- Create a composite index for the morphs columns (tokenable_type & tokenable_id)
CREATE INDEX personal_access_tokens_tokenable_index 
    ON personal_access_tokens (tokenable_type, tokenable_id);


CREATE TABLE pessoa (
  pes_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pes_nome VARCHAR(200),
  pes_data_nascimento DATE,
  pes_sexo VARCHAR(9),
  pes_mae VARCHAR(200),
  pes_pai VARCHAR(200)
);

CREATE TABLE foto_pessoa (
  fp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pes_id INTEGER NOT NULL UNIQUE REFERENCES pessoa(pes_id),
  fp_data DATE,
  fp_bucket VARCHAR(50),
  fp_hash VARCHAR(50)
);

CREATE TABLE cidade (
  cid_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cid_nome VARCHAR(200),
  cid_uf VARCHAR(2)
);

CREATE TABLE endereco (
  end_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  end_tipo_logradouro VARCHAR(50),
  end_logradouro VARCHAR(200),
  end_numero INTEGER,
  end_bairro VARCHAR(100),
  cid_id INTEGER REFERENCES cidade(cid_id)
);

CREATE TABLE pessoa_endereco (
  pes_id INTEGER REFERENCES pessoa(pes_id),
  end_id INTEGER REFERENCES endereco(end_id),
  PRIMARY KEY (pes_id, end_id)
);

CREATE TABLE servidor_temporario (
  pes_id INTEGER REFERENCES pessoa(pes_id),
  st_data_admissao DATE NOT NULL,
  st_data_demissao DATE
);

CREATE TABLE servidor_efetivo (
  pes_id INTEGER REFERENCES pessoa(pes_id),
  se_matricula VARCHAR(20)
);

CREATE TABLE unidade (
  unid_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unid_nome VARCHAR(200),
  unid_sigla VARCHAR(20)
);

CREATE TABLE lotacao (
  lot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pes_id INTEGER REFERENCES pessoa(pes_id),
  unid_id INTEGER REFERENCES unidade(unid_id),
  lot_data_lotacao DATE NOT NULL,
  lot_data_remocao DATE,
  lot_portaria VARCHAR(100)
);

CREATE TABLE unidade_endereco (
  unid_id INTEGER REFERENCES unidade(unid_id),
  end_id INTEGER REFERENCES endereco(end_id),
  PRIMARY KEY (unid_id, end_id)
);
