# Spring
spring.application.name=springapi
#spring.datasource.url=jdbc:postgresql://localhost:5432/seubanco
#spring.datasource.username=seuusuario
#spring.datasource.password=senhasegura
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# MinIO
#minio.url=http://localhost:9000
#minio.access-key=suachave
#minio.secret-key=suachavesecreta
minio.bucket-name=fotos

# JWT
# jwt.secret=supersecretkey
# jwt.expiration=300000

# AUTH
api.auth.username=${API_AUTH_USERNAME}
api.auth.password=${API_AUTH_PASSWORD}

# Server
server.port=8080

# Set root log level to DEBUG (or TRACE for more detailed logging)
# logging.level.root=DEBUG

# Optionally, you can enable detailed logs for specific packages (e.g., Spring framework)
# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate=DEBUG
# logging.level.com.yourpackage=DEBUG
